import { MigrationInterface, QueryRunner } from "typeorm";
import bcrypt from "bcrypt";

export class Auth1772082616718 implements MigrationInterface {
    name = 'Auth1772082616718'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE "users" (
                "id_user" number GENERATED BY DEFAULT AS IDENTITY,
                "username" varchar2(50) NOT NULL,
                "password" varchar2(255) NOT NULL,
                CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"),
                CONSTRAINT "PK_fbb07fa6fbd1d74bee9782fb945" PRIMARY KEY ("id_user")
            )
        `);
        const hashedPassword = await bcrypt.hash("adminadmin123", 10);

        await queryRunner.query(`
            INSERT INTO "users" ("username", "password")
            VALUES ('admin@mail.com', '${hashedPassword}')
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            DROP TABLE "users"
        `);
    }

}
