import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1772060797551 implements MigrationInterface {
    name = 'Init1772060797551'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE daf_tipos_identificacion (
                "id_tipo" number GENERATED BY DEFAULT AS IDENTITY,
                "nombre_tipo_identificacion" varchar2(255) NOT NULL,
                "codigo_tipo_identificacion" varchar2(255) NOT NULL,
                "estado" varchar2(255) NOT NULL,
                CONSTRAINT UQ_2d6d0ec5817337494f7894b7bc2 UNIQUE ("codigo_tipo_identificacion"),
                CONSTRAINT PK_6c61b103fea1e12633bbffa0f8f PRIMARY KEY ("id_tipo")
            )
        `);
        await queryRunner.query(`
            CREATE TABLE mgm_pacientes (
                "id_paciente" number NOT NULL,
                "codigo_tipo_identificacion" varchar2(255) NOT NULL,
                "numero_identificacion" varchar2(255) NOT NULL,
                "primer_nombre" varchar2(255) NOT NULL,
                "segundo_nombre" varchar2(255) NOT NULL,
                "primer_apellido" varchar2(255) NOT NULL,
                "segundo_apellido" varchar2(255) NOT NULL,
                "nombre_completo" varchar2(255) NOT NULL,
                "email" varchar2(255) NOT NULL,
                "estado" varchar2(255) NOT NULL,
                "fecha_ingreso" timestamp NOT NULL,
                "usuario_ingreso" varchar2(255) NOT NULL,
                "fecha_modificacion" timestamp NOT NULL,
                "usuario_modificacion" varchar2(255) NOT NULL,
                "id_tipo" number NOT NULL,
                CONSTRAINT PK_eddfb3e0883ae0a4d4e63e94f5c PRIMARY KEY ("id_paciente")
            )
        `);
        await queryRunner.query(`
            ALTER TABLE mgm_pacientes
            ADD CONSTRAINT FK_623d55ba60221db84ffde30726c FOREIGN KEY ("id_tipo") REFERENCES daf_tipos_identificacion ("id_tipo")
        `);

        await queryRunner.commitTransaction()

        await queryRunner.query(`
            CREATE SEQUENCE MGM_SEQ_PACIENTE
            START WITH 1
            INCREMENT BY 1
            NOCACHE
            NOCYCLE
        `);

        await queryRunner.query(`
            CREATE OR REPLACE TRIGGER mgm_pacientes_bi
            BEFORE INSERT ON mgm_pacientes
            FOR EACH ROW
            WHEN (NEW."id_paciente" IS NULL)
            BEGIN
                SELECT MGM_SEQ_PACIENTE.NEXTVAL
                INTO :NEW."id_paciente"
                FROM dual;
            END;
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            DROP TRIGGER mgm_pacientes_bi
        `);

        await queryRunner.query(`
            DROP SEQUENCE MGM_SEQ_PACIENTE
        `);

        await queryRunner.query(`
            ALTER TABLE mgm_pacientes DROP CONSTRAINT "FK_623d55ba60221db84ffde30726c"
        `);
        await queryRunner.query(`
            DROP TABLE mgm_pacientes
        `);
        await queryRunner.query(`
            DROP TABLE daf_tipos_identificacion
        `);
    }

}
